"""empty message

Revision ID: 44970b71a141
Revises: 
Create Date: 2022-05-08 18:57:31.041832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44970b71a141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nature_name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_name', sa.String(length=250), nullable=False),
    sa.Column('favorite_uid', sa.Integer(), nullable=False),
    sa.Column('favorite_nature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_nature'], ['nature.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('favorite_name'),
    sa.UniqueConstraint('user_id', 'favorite_name', 'favorite_uid', 'favorite_nature', name='debe_tener_una_sola_coincidencia')
    )
    op.create_table('person',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=250), nullable=True),
    sa.Column('person_nature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_nature'], ['nature.id'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('person_name')
    )
    op.create_table('planet',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=250), nullable=True),
    sa.Column('planet_nature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_nature'], ['nature.id'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('planet_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    op.drop_table('person')
    op.drop_table('favorite')
    op.drop_table('user')
    op.drop_table('nature')
    # ### end Alembic commands ###
